// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ListDevices():Promise<Array<app.DeviceInfo>>;

export function PauseCapture():Promise<void>;

export function RestartReading(arg1:string):Promise<void>;

export function ResumeCapture():Promise<void>;

export function Start(arg1:string,arg2:string):Promise<void>;

export function Stop():Promise<void>;
