// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetDetail(arg1:number):Promise<void>;

export function ListDevices():Promise<Array<app.DeviceInfo>>;

export function PauseCapture():Promise<void>;

export function ResumeCapture():Promise<void>;

export function StartCapture(arg1:string):Promise<void>;

export function StartReader(arg1:string):Promise<void>;

export function StopCapture():Promise<void>;

export function StopReader():Promise<void>;

export function SwitchToDev():Promise<void>;
