// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['app']['T']['Greet'](arg1);
}

export function ListDevices() {
  return window['go']['app']['T']['ListDevices']();
}

export function PauseCapture() {
  return window['go']['app']['T']['PauseCapture']();
}

export function RestartReading(arg1) {
  return window['go']['app']['T']['RestartReading'](arg1);
}

export function ResumeCapture() {
  return window['go']['app']['T']['ResumeCapture']();
}

export function Start(arg1, arg2) {
  return window['go']['app']['T']['Start'](arg1, arg2);
}

export function Stop() {
  return window['go']['app']['T']['Stop']();
}
