// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['app']['T']['Get'](arg1);
}

export function ListDevices() {
  return window['go']['app']['T']['ListDevices']();
}

export function PauseCapture() {
  return window['go']['app']['T']['PauseCapture']();
}

export function ResumeCapture() {
  return window['go']['app']['T']['ResumeCapture']();
}

export function StartCapture(arg1) {
  return window['go']['app']['T']['StartCapture'](arg1);
}

export function StartReader(arg1) {
  return window['go']['app']['T']['StartReader'](arg1);
}

export function StopCapture() {
  return window['go']['app']['T']['StopCapture']();
}

export function StopReader() {
  return window['go']['app']['T']['StopReader']();
}

export function SwitchToDev() {
  return window['go']['app']['T']['SwitchToDev']();
}
